name: dartexify_cli
description: A Dart CLI tool for creating LaTeX projects.
version: 0.0.1-dev
repository: https://github.com/Abdulrasheed1729/dartexify

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  args: ^2.3.1
  cli_completion: ^0.3.0
  mason: ^0.1.0-dev.49
  mason_logger: ^0.2.4
  meta: ^1.9.1
  path: ^1.8.3
  pub_updater: ^0.3.0
  universal_io: ^2.2.0
  usage: ^4.1.1

dev_dependencies:
  build_runner: ^2.0.0
  build_verify: ^3.0.0
  build_version: ^2.0.0
  mocktail: ">=0.3.0 <2.0.0"
  test: ^1.19.2
  very_good_analysis: ">=4.0.0 <6.0.0"

executables:
  ? dartexify
